### ISSUE TITLE
Properly handle special character in S3 filename

### ISSUE THREAD

**Issue by nicnguyen3103** [jkausti/target-s3#6]
The NOW.timestamp() in the parquet file, in some cases, may need special treatment to be read by script and open source application.  Here are some examples of the issue: 

1. https://stackoverflow.com/questions/34093098/load-a-amazon-s3-file-which-has-colons-within-the-filename-through-pyspark
2. https://support.dremio.com/hc/en-us/articles/13074736678299-Use-of-colon-in-S3-pathnames-causes-Relative-path-in-absolute-URI-error (this is the one that I am currently having an issue with) 
3. https://github.com/aws/aws-cli/issues/1154, window system having a hardtime dealing with colon

I understand that these issues can be resolved with some code changes, but since the target-s3 is a barebone ELT framework, should the filename be more standardized to be read by all applications without special treatment? 

The PR below is just a quickfix by replacing the timestamp. I think we should consider about the naming approach.

https://github.com/jkausti/target-s3/pull/5

**Comment by jkausti** [comment]
Thanks! I merged the PR now so I will close this issue too.

Thanks for your contribution, @nicnguyen3103 !

**Comment by nicnguyen3103** [comment]
Hi @jkausti ,
Many thanks for your suggestion. Have a nice day!
